### PR TITLE
Feat/get data

### PR DESCRIPTION
**Pull request by openmichael**
@James9446 @Chazie9 @ChaseWNorton 
Because I think that we will be focusing on the frontend. I made a change to my database so that the information is stored in the same table, in this way it's easier to retrieve data. 
I also modified the code, so now it will render with data that is retrieved by a get request to the server by the client.

### CODE REVIEW

**Comment by openmichael** [comment]
@James9446 @Chazie9 @ChaseWNorton 
I added another feature to show the time difference. Rather than just showing the date it now shows the actual time difference between now and the time a comment or reply was created.

**Review by James9446 — APPROVED** [review]
Time difference feature is very cool.

**Review by James9446 — APPROVED** [review]
Oh nice so now you can take in an id and get the corresponding data. Is that right?

**Comment by ChaseWNorton** [comment]
Really cool stuff Michael!

**Comment by openmichael** [comment]
@James9446 Yes, I can pass in a product ID and show its corresponding comments and replies.

**Pull request merged**
